server:
  port: 8084

spring:
  application:
    name: board-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ROIMSG}
    username: ${DB_USER:roit}
    password: ${DB_PASSWORD:fhdlxpzm1*}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

jwt:
  secret: ${JWT_SECRET:your_super_secret_jwt_key_here_change_this_in_production}