server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    open-in-view: false
  
  h2:
    console:
      enabled: true
      path: /h2-console

# JWT
jwt:
  secret: ${JWT_SECRET:your_super_secret_jwt_key_here_change_this_in_production}

logging:
  level:
    com.roimsg.user: DEBUG