server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ROIMSG}
    username: ${DB_USER:roit}
    password: ${DB_PASSWORD:fhdlxpzm1*}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    open-in-view: false

# JWT
jwt:
  secret: ${JWT_SECRET:your_super_secret_jwt_key_here_change_this_in_production}

logging:
  level:
    com.roimsg.user: DEBUG