/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToastEditor: typeof import('./src/components/ToastEditor.vue')['default']
    ToastFileUploader: typeof import('./src/components/ToastFileUploader.vue')['default']
    ToastGrid: typeof import('./src/components/ToastGrid.vue')['default']
    VListItemIcon: typeof import('vuetify/components')['VListItemIcon']
  }
}
