server:
  port: 8085

spring:
  application:
    name: file-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ROIMSG}
    username: ${DB_USER:roit}
    password: ${DB_PASSWORD:fhdlxpzm1*}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

jwt:
  secret: ${JWT_SECRET:your_super_secret_jwt_key_here_change_this_in_production}

file:
  upload:
    path: ${UPLOAD_PATH:D:\\Data}
    allowed-types: ${ALLOWED_FILE_TYPES:jpg,jpeg,png,gif,pdf,txt,doc,docx,xls,xlsx,ppt,pptx}
    denied-extensions: ${DENIED_EXTENSIONS:exe,bat,cmd,sh,msi,dll,com,jar,js,vbs,ps1}
