server:
  port: 8085

spring:
  application:
    name: file-service

  datasource:
    url: jdbc:h2:mem:filedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    open-in-view: false
  
  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

jwt:
  secret: ${JWT_SECRET:your_super_secret_jwt_key_here_change_this_in_production}

file:
  upload:
    path: ${UPLOAD_PATH:D:\\Data}
    allowed-types: ${ALLOWED_FILE_TYPES:jpg,jpeg,png,gif,pdf,txt,doc,docx,xls,xlsx,ppt,pptx}
    denied-extensions: ${DENIED_EXTENSIONS:exe,bat,cmd,sh,msi,dll,com,jar,js,vbs,ps1}
